# Generated by Django 5.1.1 on 2024-09-09 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_nome', models.CharField(max_length=255, verbose_name='Nome da categoria')),
            ],
            options={
                'verbose_name': 'Categorias',
                'ordering': ['categoria_nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_nome', models.CharField(max_length=255, verbose_name='Nome do produto')),
                ('produto_marca', models.CharField(max_length=255, verbose_name='Marca do produto')),
                ('produto_preco_a_vista', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Preço a vista do produto')),
                ('produto_preco_parcelado', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Preço parcelado do produto')),
                ('produto_quantidade_em_estoque', models.IntegerField(verbose_name='Quantidade em estoque do produto')),
                ('produto_codigo', models.IntegerField(unique=True, verbose_name='Código do produto')),
                ('produto_ponto_reposicao', models.IntegerField(verbose_name='Ponto de reposição do produto')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['produto_nome'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(max_length=255, verbose_name='Nome do cliente')),
                ('cliente_apelido', models.CharField(max_length=127, verbose_name='Apelido do cliente')),
                ('cliente_cnpj', models.CharField(blank=True, max_length=14, null=True, verbose_name='CNPJ do cliente')),
                ('cliente_cpf', models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF do cliente')),
                ('cliente_email', models.EmailField(blank=True, max_length=127, null=True, verbose_name='Email do cliente')),
                ('endereco_numero', models.CharField(max_length=31, verbose_name='Numero do endereço')),
                ('endereco_rua', models.CharField(max_length=127, verbose_name='Rua do endereço')),
                ('endereco_bairro', models.CharField(max_length=127, verbose_name='Bairro do endereço')),
                ('endereco_cidade', models.CharField(max_length=127, verbose_name='Cidade do endereço')),
                ('endereco_estado', models.CharField(max_length=127, verbose_name='Estado do endereço')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'constraints': [models.UniqueConstraint(models.F('cliente_cpf'), name='cliente_cpf_unico'), models.UniqueConstraint(models.F('cliente_cnpj'), name='cliente_cnpj_unico')],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor_nome', models.CharField(max_length=255, verbose_name='Nome do fornecedor')),
                ('fornecedor_cnpj', models.CharField(blank=True, max_length=14, null=True, verbose_name='CNPJ do fornecedor')),
                ('fornecedor_cpf', models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF do fornecedor')),
                ('fornecedor_email', models.EmailField(max_length=127, verbose_name='Email do fornecedor')),
                ('endereco_numero', models.CharField(max_length=31, verbose_name='Numero do endereço')),
                ('endereco_rua', models.CharField(max_length=127, verbose_name='Rua do endereço')),
                ('endereco_bairro', models.CharField(max_length=127, verbose_name='Bairro do endereço')),
                ('endereco_cidade', models.CharField(max_length=127, verbose_name='Cidade do endereço')),
                ('endereco_estado', models.CharField(max_length=127, verbose_name='Estado do endereço')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'constraints': [models.UniqueConstraint(models.F('fornecedor_cpf'), name='fornecedor_cpf_unico'), models.UniqueConstraint(models.F('fornecedor_cnpj'), name='fornecedor_cnpj_unico')],
            },
        ),
        migrations.CreateModel(
            name='TelefoneCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=14, verbose_name='Telefone do fornecedor')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construcmanager.cliente')),
            ],
            options={
                'verbose_name': 'Telefone',
                'verbose_name_plural': 'Telefones',
            },
        ),
        migrations.CreateModel(
            name='TelefoneFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=14, verbose_name='Telefone do fornecedor')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construcmanager.fornecedor')),
            ],
            options={
                'verbose_name': 'Telefone',
                'verbose_name_plural': 'Telefones',
            },
        ),
        migrations.CreateModel(
            name='ProdutoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construcmanager.categoria')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construcmanager.produto')),
            ],
            options={
                'verbose_name': 'Junção entre Produto e Categoria',
                'verbose_name_plural': 'Junções entre Produto e Categoria',
                'unique_together': {('produto', 'categoria')},
            },
        ),
        migrations.CreateModel(
            name='ProdutoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construcmanager.fornecedor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construcmanager.produto')),
            ],
            options={
                'verbose_name': 'Junção entre produto e fornecedor',
                'verbose_name_plural': 'Junções entre produto e fornecedor',
                'unique_together': {('produto', 'fornecedor')},
            },
        ),
    ]
