# Generated by Django 5.1.1 on 2024-12-08 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construcmanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='compra_pagamanento_data',
            new_name='compra_pagamento_data',
        ),
    ]
